### PR TITLE
Dynamic Attributes Lazy Loading Backport

### PR DESCRIPTION
**Pull request by jsolari56**
Backported keeping the code as similar as possible to master.

### CODE REVIEW

**Comment by puneetbehl** [comment]
Can you please add tests related to this change?

**Comment by jsolari56** [comment]
In SchemalessSpec the following tests are using this code:

"dynamic properties point to domain classes instance should be relationships"
"test clear dynamic collection association"
"dynamic properties pointing to arrays of domain classes should be a relationship"
"Test update dynamic single-ended relationships"

May be we can also check with multiple objects in the same session. I had an issue with that.

**Comment by jsolari56** [comment]
@puneetbehl May you take a look ?

**Comment by amadfida** [comment]
@puneetbehl any thoughts on this?

**Comment by puneetbehl** [comment]
@jsolari56 Right now, I am working on some recent PR on Grails Data Mapping which broke the other builds. I will look into this as soon as I am done with those. Also, I don't work on weekends.

**Comment by amadfida** [comment]
@puneetbehl - Thanks for you feedback, let us know if you have any questions.

**Pull request merged**
